name: Build and Deploy Catalog from Tag

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  LANG: en_US.UTF-8
  MAVEN_OPTS: -Xmx3000m
  MAVEN_ARGS: -V -ntp -Dhttp.keepAlive=false -DskipTests=true -e

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set versions
        run: |
          export C_VERSION="${GITHUB_REF_NAME#v}" 
          export C_REVISION="${GITHUB_SHA}" 
          
          echo "CONNECTORS_VERSION=${C_VERSION}" >> $GITHUB_ENV
          echo "CONNECTORS_REVISION=${C_REVISION}" >> $GITHUB_ENV
          echo "CONNECTORS_RELEASE=${C_VERSION}.${C_REVISION}" >> $GITHUB_ENV

      - name: Build Connector Images
        run: |
          ./mvnw ${MAVEN_ARGS} clean install \
            -Dcos.connector.container.tag="${CONNECTORS_RELEASE}" \
            -Pcontainer-build

      - name: Regen
        run: |
          ./gen_manifests.sh

      - name: Build Catalog Image
        run: |
          docker build -t "quay.io/rhoas/cos-fleet-catalog-camel:${CONNECTORS_RELEASE}" -f etc/Dockerfile.catalog .

      - name: List Images
        run: |
          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep quay.io/rhoas/cos-

      - name: Regen
        run: |
          ./gen_manifests.sh

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_MCI_USR }}
          password: ${{ secrets.QUAY_MCI_PWD }}

      - name: Push Images
        run: |
          IMAGES=$(docker image ls --format "{{.Repository}}:{{.Tag}}" | grep quay.io/rhoas/cos-)
          for IMAGE in ${IMAGES}; do
              docker push $IMAGE
          done

      - name: "Create Release Branch for tag {{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: release-${{ env.CONNECTORS_RELEASE }}
        run: |
          echo ""
          echo "tag     : ${{ github.ref_name }}"
          echo "release : ${CONNECTORS_RELEASE}"
          echo "branch  : ${BRANCH_NAME}"
          echo ""

          git config user.email "mas-connectors@redhat.com" 
          git config user.name "mas-connectors"

          git checkout -b "${BRANCH_NAME}"
          git add .
          git commit -am "Create release branch for tag ${{ github.ref_name }}"
          git reset --hard
          git push -u origin "${BRANCH_NAME}"

  kustomize:
    needs: "build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        overlay:
          - "staging"
    steps:
      - name: Set versions
        run: |
          export C_VERSION="${GITHUB_REF_NAME#v}" 
          export C_REVISION="${GITHUB_SHA}" 
          
          echo "CONNECTORS_VERSION=${C_VERSION}" >> $GITHUB_ENV
          echo "CONNECTORS_REVISION=${C_REVISION}" >> $GITHUB_ENV
          echo "CONNECTORS_RELEASE=${C_VERSION}.${C_REVISION}" >> $GITHUB_ENV

      - name: "Checkout cos-manifests project"
        uses: actions/checkout@v2
        with:
          repository: bf2fc6cc711aee1a0c2a/cos-manifests
          token: ${{ secrets.GH_TOKEN }}

      - name: "Update Kustomize overlay ${{ matrix.overlay }}"
        uses: mikefarah/yq@master
        env:
          OVERLAY_PATH: kustomize/overlays/${{ matrix.overlay }}/control-plane/cos-fleet-catalog-camel
        with:
          cmd: |
            yq -i '.images[0].newTag = strenv(CONNECTORS_RELEASE)' ${OVERLAY_PATH}/kustomization.yaml

      - name: "Create PR for ${{ matrix.overlay }}"
        env:
          OVERLAY_PATH: kustomize/overlays/${{ matrix.overlay }}/control-plane/cos-fleet-catalog-camel
          BRANCH_NAME: "cos-fleet-catalog-camel.${{ matrix.overlay }}.${{ env.CONNECTORS_RELEASE }}"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo ""
          echo "tag      : ${{ github.ref_name }}"
          echo "version  : ${CONNECTORS_VERSION}"
          echo "revision : ${CONNECTORS_REVISION}"
          echo "release  : ${CONNECTORS_RELEASE}"
          echo "branch   : ${BRANCH_NAME}"
          echo ""

          git config user.email "mas-connectors@redhat.com" 
          git config user.name "mas-connectors"

          git checkout -b ${BRANCH_NAME}
          git add ${OVERLAY_PATH}
          git commit -m "Update cos-fleet-catalog-camel kustomization images for overlay ${{ matrix.overlay }}" ${OVERLAY_PATH}
          git reset --hard
          git push -u origin ${BRANCH_NAME}

          # GH CLI can't find the branch on remote... needs some time :)
          sleep 15

          gh config set prompt disabled

          gh pr create \
            --fill \
            --base main \
            --title "chore(kustomize): update cos-fleet-catalog-camel kustomization images overlay ${{ matrix.overlay }}" \
            --body "sha ${{ github.sha }}, overlay: ${{ matrix.overlay }}, tag: ${{ github.ref_name }}"